### ISSUE TITLE
Błąd przy imporcie pliku csv z BB 2.0

### ISSUE THREAD

**Issue by juhacz** [stasbar/tax-ledger-cli#1]
Przy próbie importu pliku z BB 2.0 dostaję tylko błąd:

Wpisz akcje do wykonania> transakcje -oldbb oldbitbay.csv
Exception in thread "main" java.lang.IllegalArgumentException: Could not map ZapĹ?ata za zakup waluty to OperationType
        at com.stasbar.taxledger.writers.BitBayCsvReaderKt.parseOperationType(BitBayCsvReader.kt:60)
        at com.stasbar.taxledger.writers.BitBayCsvReaderKt.toTransaction(BitBayCsvReader.kt:42)
        at com.stasbar.taxledger.writers.BitBayCsvReader.readCsv(BitBayCsvReader.kt:120)
        at com.stasbar.taxledger.MainKt.performTransactionsAction(Main.kt:453)
        at com.stasbar.taxledger.MainKt.performActions(Main.kt:397)
        at com.stasbar.taxledger.MainKt.main(Main.kt:92)

**Comment by dambo1993** [comment]
Również potwierdzam ten błąd - dodam, ze pracuję na windows 7.

**Comment by juhacz** [comment]
Ja na Win10x64

**Comment by juhacz** [comment]
Tutaj zawartość pliku, na którym program się wywala

https://pastebin.com/Mj6FGT1e

**Comment by stasbar** [comment]
Dzięki za zgłoszenie błędu. Z tego co widzę to problem jest w polskich znakach i Windowsie który nie potrafi ich dobrze odczytać. Poprawione w wersji 1.0.7, zapraszam do [pobierania](https://github.com/stasbar/tax-ledger-cli/releases/tag/v1.0.7) :)
